import type { Metadata } from 'next'
import './globals.css'
import { AuthProvider } from './context/AuthContext'

import { Wix_Madefor_Display } from 'next/font/google'
import { handleUserId } from './utils/generateId'

//👇 Configure our font object
const wixMadeForDisplay = Wix_Madefor_Display({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-wix-made-for-display',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <AuthProvider>
            <html lang="en" className={`${wixMadeForDisplay.className}`}>
                <body>{children}</body>
            </html>
        </AuthProvider>
    )
}
