import type { Metadata } from 'next'
import './globals.css'

import { Wix_Madefor_Display } from 'next/font/google'

//👇 Configure our font object
const wixMadeForDisplay = Wix_Madefor_Display({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-wix-made-for-display',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={`${wixMadeForDisplay.className}`}>
          
            <body>{children}</body>
        </html>
    )
}
